### ISSUE TITLE
Security vulnerability in dependencies: https-proxy-agent

### ISSUE THREAD

**Issue by kevcenteno** [danjenkins/node-saucelabs#38]
https-proxy-agent ^1.0.0 has a security vulnerability.  The fix is to upgrade to >=2.2.0 Details can be found here: https://nodesecurity.io/advisories/593

**Comment by unindented** [comment]
Can you open a PR?

**Comment by qiyigg** [comment]
Opened a PR(#39) for it. Thanks.

**Comment by unindented** [comment]
Fixed with version `1.5.0`.

**Comment by qiyigg** [comment]
Thanks!!

**Comment by brettz9** [comment]
Can this be closed then?
